"""`evals/regression/check.py <record> <properties.json>` -- the regression checker (#877, slice 2 of #870).

Every behavioural test runs the DOCUMENTED gesture, exactly this argv and nothing stronger:

    python3 evals/regression/check.py <record> <properties.json>

as a subprocess (`sys.executable`, no extra flag). No test imports a check function to get its
pass/fail verdict; the in-process module is used only for its seam (`INTERNAL`), the way
`test_regression_record.py` does for the builder.

The committed record and the three mutated copies under `evals/regression/fixtures/` are
regenerated by `tests/regression_fixture.py` and byte-compared here, so they cannot rot.
"""
import copy
import importlib.util
import json
import pathlib
import re
import subprocess
import sys
import tempfile

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tests"))
import regression_fixture as fx  # noqa: E402

CHECK = ROOT / "evals" / "regression" / "check.py"
PROPS = ROOT / "evals" / "regression" / "properties.json"
FIXDIR = ROOT / "evals" / "regression" / "fixtures"
FAMILIES = {"outcome", "process", "cost", "quality", "safety"}
IDS = ["outcome.goal_merged", "outcome.verify_exit_zero", "outcome.goal_commits_on_main",
       "process.phase_ends_recorded", "process.plan_review_verdict_approved",
       "process.review_marker_in_store", "cost.tokens_measured", "cost.spend_positive",
       "quality.test_first_passed", "quality.plan_and_research_present", "safety.only_internal_kinds",
       "safety.no_absolute_paths", "safety.caveats_present"]
LINE = re.compile(r"^(PASS|FAIL|NOT EVALUABLE)\s+(\S+)(.*)$")

_spec = importlib.util.spec_from_file_location("regression_check", CHECK)


def _load_check():
    mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------- helpers


@pytest.fixture(scope="module")
def green_record():
    with tempfile.TemporaryDirectory() as tmp:
        return fx.build_green_record(tmp)


def _run(record, props=PROPS):
    """The documented gesture: python3 evals/regression/check.py <record> <properties.json>."""
    return subprocess.run([sys.executable, str(CHECK), str(record), str(props)],
                          capture_output=True, text=True, timeout=60)


def _write(path, obj):
    path.write_text(json.dumps(obj, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    return path


def _check_rec(tmp_path, rec, props=PROPS):
    return _run(_write(tmp_path / "rec.json", rec), props)


def _words(proc):
    out = {}
    for line in proc.stdout.splitlines():
        m = LINE.match(line)
        if m:
            out[m.group(2)] = (m.group(1), m.group(3))
    return out


def _props_file(tmp_path, *entries):
    return _write(tmp_path / "props.json", {"properties": list(entries)})


def _prop(**over):
    base = {"id": "process.x", "family": "process", "hard": True, "stream": "action_log",
            "check": "log_row", "kinds": ["merged"], "match": {}, "why": "x"}
    base.update(over)
    return base


def _assert_refused(proc):
    assert proc.returncode == 2, (proc.returncode, proc.stdout, proc.stderr)
    assert proc.stdout == ""
    assert "check.py: REFUSED:" in proc.stderr


def _assert_only(proc, pid, word):
    words = _words(proc)
    assert proc.returncode == 1, proc.stdout
    assert words[pid][0] == word, proc.stdout
    others = {k: v[0] for k, v in words.items() if k != pid}
    assert all(v == "PASS" for v in others.values()), proc.stdout


# --------------------------------------------------------------------------- core


def test_cli_green_record_exits_zero_all_pass_via_subprocess(tmp_path, green_record):
    proc = _check_rec(tmp_path, green_record)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert all(w == "PASS" for w, _ in _words(proc).values()), proc.stdout


def test_output_names_each_property_with_one_of_three_words(tmp_path, green_record):
    proc = _check_rec(tmp_path, green_record)
    assert sorted(_words(proc)) == sorted(IDS), proc.stdout


def test_missing_record_file_refuses_exit_2(tmp_path):
    _assert_refused(_run(tmp_path / "nope.json"))


def test_malformed_json_record_refuses_exit_2(tmp_path):
    p = tmp_path / "rec.json"
    p.write_text("{not json", encoding="utf-8")
    _assert_refused(_run(p))


def test_wrong_schema_refuses_exit_2(tmp_path, green_record):
    rec = dict(green_record, schema="sigma.regression-run/v0")
    _assert_refused(_check_rec(tmp_path, rec))


def test_record_without_streams_refuses_exit_2(tmp_path, green_record):
    rec = {k: v for k, v in green_record.items() if k != "streams"}
    _assert_refused(_check_rec(tmp_path, rec))


# --------------------------------------------------------------------------- property list


def test_properties_json_covers_the_five_families():
    props = json.loads(PROPS.read_text(encoding="utf-8"))["properties"]
    assert {p["family"] for p in props} == FAMILIES


def test_properties_ids_unique_and_documented_fields_present():
    props = json.loads(PROPS.read_text(encoding="utf-8"))["properties"]
    ids = [p["id"] for p in props]
    assert len(ids) == len(set(ids))
    assert sorted(ids) == sorted(IDS)                      # the id list is a contract for slice 4
    for p in props:
        assert {"id", "family", "hard", "stream", "check", "why"} <= set(p), p["id"]
        assert isinstance(p["hard"], bool) and p["why"]


def test_every_property_kind_is_internal():
    internal = _load_check().INTERNAL
    props = json.loads(PROPS.read_text(encoding="utf-8"))["properties"]
    for p in props:
        for k in p.get("kinds", []):
            assert k in internal, (p["id"], k)


# --------------------------------------------------------------------------- operators


def test_absent_hard_stream_prints_not_evaluable_and_exits_1(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["action_log"]["present"] = False
    proc = _check_rec(tmp_path, rec)
    assert proc.returncode == 1, proc.stdout
    assert _words(proc)["outcome.goal_merged"][0] == "NOT EVALUABLE", proc.stdout


def test_absent_soft_stream_prints_not_evaluable_and_exits_0(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["tokens"]["present"] = False
    proc = _check_rec(tmp_path, rec)
    assert proc.returncode == 0, proc.stdout
    words = _words(proc)
    assert words["cost.tokens_measured"][0] == "NOT EVALUABLE", proc.stdout
    assert words["cost.spend_positive"][0] == "NOT EVALUABLE", proc.stdout


def test_any_fail_exits_1_and_names_the_property(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["verify"]["test_first_passed"] = False      # a SOFT property failing still exits 1
    _assert_only(_check_rec(tmp_path, rec), "quality.test_first_passed", "FAIL")


def test_phase_ends_fail_names_the_missing_phase(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rows = rec["streams"]["action_log"]["rows"]
    rec["streams"]["action_log"]["rows"] = [r for r in rows if not (
        r["kind"] == "phase" and r["phase"] == "plan" and r["state"] == "end")]
    proc = _check_rec(tmp_path, rec)
    _assert_only(proc, "process.phase_ends_recorded", "FAIL")
    assert "plan" in _words(proc)["process.phase_ends_recorded"][1]


def test_review_marker_false_in_store_fails(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["review_evidence"]["marker_in_store"] = False
    _assert_only(_check_rec(tmp_path, rec), "process.review_marker_in_store", "FAIL")


def test_verify_nonzero_exit_fails(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["verify"]["exit"] = 1
    _assert_only(_check_rec(tmp_path, rec), "outcome.verify_exit_zero", "FAIL")


def test_goal_commit_not_on_main_fails(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    branch = next(iter(rec["streams"]["commit_order"]["goal_branches"].values()))
    branch.append({"sha": "f" * 40, "subject": "unlanded"})
    _assert_only(_check_rec(tmp_path, rec), "outcome.goal_commits_on_main", "FAIL")


def test_absolute_path_in_record_fails_safety(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["verify"]["head"] = "/Users/someone/secret/dir"
    _assert_only(_check_rec(tmp_path, rec), "safety.no_absolute_paths", "FAIL")


def test_missing_call_existence_caveat_fails_safety(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["caveats"] = []
    _assert_only(_check_rec(tmp_path, rec), "safety.caveats_present", "FAIL")


def test_agent_kind_row_in_log_fails_safety_property(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    rec["streams"]["action_log"]["rows"].append({"kind": "agent_dispatch", "ts": "2026-01-01T00:59:00.000Z"})
    _assert_only(_check_rec(tmp_path, rec), "safety.only_internal_kinds", "FAIL")


# --------------------------------------------------------------------------- AC-3 / PC-11 guards


@pytest.mark.parametrize("kind", fx.record._load_scripts("actionlog").AGENT_KINDS)
def test_property_naming_agent_kind_is_refused_exit_2(tmp_path, green_record, kind):
    props = _props_file(tmp_path, _prop(kinds=[kind]))
    proc = _check_rec(tmp_path, green_record, props)
    _assert_refused(proc)
    assert kind in proc.stderr


def test_internal_kinds_loaded_not_copied():
    mod = _load_check()
    actionlog = mod.record._load_scripts("actionlog")
    assert mod.INTERNAL is actionlog.INTERNAL_KINDS            # the same object, never a copy


def test_process_property_ignores_journal_derived_phases(tmp_path, green_record):
    rec = copy.deepcopy(green_record)
    assert any(p["phase"] == "review" and p["end_present"] for p in rec["phases"])   # journal side intact
    rows = rec["streams"]["action_log"]["rows"]
    rec["streams"]["action_log"]["rows"] = [r for r in rows if not (
        r["kind"] == "phase" and r["phase"] == "review" and r["state"] == "end")]
    proc = _check_rec(tmp_path, rec)
    _assert_only(proc, "process.phase_ends_recorded", "FAIL")
    assert "review" in _words(proc)["process.phase_ends_recorded"][1]


def test_unknown_operator_or_family_refuses_exit_2(tmp_path, green_record):
    _assert_refused(_check_rec(tmp_path, green_record, _props_file(tmp_path, _prop(check="bogus_op"))))
    _assert_refused(_check_rec(tmp_path, green_record, _props_file(tmp_path, _prop(family="bogus_family"))))


def test_duplicate_property_id_refuses_exit_2(tmp_path, green_record):
    _assert_refused(_check_rec(tmp_path, green_record, _props_file(tmp_path, _prop(), _prop())))


def test_property_missing_a_field_refuses_exit_2(tmp_path, green_record):
    p = _prop()
    del p["why"]
    _assert_refused(_check_rec(tmp_path, green_record, _props_file(tmp_path, p)))


# --------------------------------------------------------------------------- recorded run + mutations


def test_committed_green_fixture_matches_regeneration():
    with tempfile.TemporaryDirectory() as tmp:
        fx.write_fixtures(tmp)
        for name in fx.FIXTURE_FILES:
            assert (pathlib.Path(tmp) / name).read_bytes() == (FIXDIR / name).read_bytes(), name
    green = json.loads((FIXDIR / "run-green.json").read_text(encoding="utf-8"))
    assert green["run"] == "run"
    assert not any(re.search(r"(?<![\w.])/[\w.@+~-]+/", s) for s in _strings(green))


def test_green_fixture_has_every_stream_present():
    green = json.loads((FIXDIR / "run-green.json").read_text(encoding="utf-8"))
    assert set(green["streams"]) and all(s["present"] is True for s in green["streams"].values())


def test_check_exits_zero_on_committed_green_fixture():
    proc = _run(FIXDIR / "run-green.json")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert sorted(_words(proc)) == sorted(IDS)


def test_mutation_drop_verdict_not_evaluable_names_property_exit_1():
    proc = _run(FIXDIR / "run-drop-verdict.json")
    _assert_only(proc, "process.plan_review_verdict_approved", "NOT EVALUABLE")


def test_mutation_drop_phase_end_fails_names_review_exit_1():
    proc = _run(FIXDIR / "run-drop-phase-end.json")
    _assert_only(proc, "process.phase_ends_recorded", "FAIL")
    assert "review" in _words(proc)["process.phase_ends_recorded"][1]


def test_mutation_drop_marker_not_evaluable_names_property_exit_1():
    proc = _run(FIXDIR / "run-drop-marker.json")
    _assert_only(proc, "process.review_marker_in_store", "NOT EVALUABLE")


def test_committed_mutations_match_regeneration(green_record):
    for name, mutator in fx.FIXTURE_FILES.items():
        if mutator is None:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            out = pathlib.Path(tmp) / name
            fx.record.write_atomic(out, getattr(fx, mutator)(green_record))
            assert out.read_bytes() == (FIXDIR / name).read_bytes(), name


def _strip(rec, section, drop_phase=None, drop_row=None):
    """A copy of `rec` with exactly the named evidence removed: a whole stream, a phases[] entry, a log row."""
    out = copy.deepcopy(rec)
    if section:
        del out["streams"][section]
    if drop_phase:
        out["phases"] = [p for p in out["phases"] if p["phase"] != drop_phase]
    if drop_row:
        rows = out["streams"]["action_log"]["rows"]
        out["streams"]["action_log"]["rows"] = [r for r in rows if not all(r.get(a) == b for a, b in drop_row.items())]
    return out


def _strings(node):
    if isinstance(node, str):
        yield node
    elif isinstance(node, dict):
        for k, v in node.items():
            yield k
            for s in _strings(v):
                yield s
    elif isinstance(node, list):
        for v in node:
            for s in _strings(v):
                yield s


def test_each_mutation_differs_from_green_by_exactly_one_deletion():
    """Deleting the ONE piece of evidence from green by hand leaves the same tree as the mutated copy
    with that same piece deleted: nothing else moved, nothing was added elsewhere."""
    green = json.loads((FIXDIR / "run-green.json").read_text(encoding="utf-8"))
    cases = {
        "run-drop-verdict.json": dict(section="plan_review_verdict",
                                      drop_row={"kind": "verdict", "phase": "plan_review"}),
        "run-drop-phase-end.json": dict(section=None, drop_phase="review",
                                        drop_row={"kind": "phase", "phase": "review", "state": "end"}),
        "run-drop-marker.json": dict(section="review_evidence"),
    }
    for name, kw in cases.items():
        mut = json.loads((FIXDIR / name).read_text(encoding="utf-8"))
        assert mut != green, name
        a = _strip(green, **kw)
        b = _strip(mut, kw["section"], None, None) if kw.get("drop_row") is None else \
            _strip(mut, kw["section"], kw.get("drop_phase"), kw.get("drop_row"))
        assert a == b, name
